# name: Continuous Deployment

# on:
#   push:
#     branches:
#       - release  # Adjust this to match your main branch name

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # - name: Install Node.js
#       #   uses: actions/setup-node@v2
#       #   with:
#       #     node-version: 14  # Adjust to your Node.js version

#       # - name: Install project dependencies
#       #   run: |
#       #     cd path/to/your/app
#       #     npm install

#       - name: Deploy to Oracle Ubuntu
#         run: |
#           ssh -i ubuntu@IP "cd /home/ubuntu/Projects/SMS32-OL && git pull origin release"
#         env:
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key as a secret in your repository

